spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/usedTrade
    driver-class-name: org.mariadb.jdbc.Driver
    username: usedTradeUser
    password: 1111
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: honee85832@gmail.com
    password: tyiliabvgyqjpple
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

logging:
  level:
    root: info

#mybatis:
#  mapper-locations: mybatis/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

